import './global.css'
import Link from "next/link";
import {Roboto_Mono} from 'next/font/google'

const robotoMono = Roboto_Mono({subsets: ['latin']})
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={robotoMono.className}>
      <div className="header-container">
          <Link href='/'>HOME</Link>
          <Link href='/about'>ABOUT ME</Link>
          <Link href='/portfolio'>PORTFOLIO</Link>
          <Link href='/contacts'>CONTACTS</Link>
          <Link href='/comic'>COMIC</Link>
      </div>
      {children}

      </body>

      </html>
  )
}
